;;*****************************************************************************
;;*****************************************************************************
;;  FILENAME: stateTimerINT.asm
;;   Version: 2.6, Updated on 2015/3/4 at 22:27:48
;;  Generated by PSoC Designer 5.4.3191
;;
;;  DESCRIPTION: Timer32 Interrupt Service Routine
;;-----------------------------------------------------------------------------
;;  Copyright (c) Cypress Semiconductor 2015. All Rights Reserved.
;;*****************************************************************************
;;*****************************************************************************

include "m8c.inc"
include "memory.inc"
include "stateTimer.inc"


;-----------------------------------------------
;  Global Symbols
;-----------------------------------------------
export  _stateTimer_ISR


AREA InterruptRAM (RAM,REL,CON)

;@PSoC_UserCode_INIT@ (Do not change this line.)
;---------------------------------------------------
; Insert your custom declarations below this banner
;---------------------------------------------------

;------------------------
; Includes
;------------------------

	
;------------------------
;  Constant Definitions
;------------------------
stateTimerMilisec: equ 0x22
stateTimerSeconds: equ 0x23
stateTimerMinutes: equ 0x24
stateTimerHour: equ 0x25
stateTimerAccuracy: equ 0x26

;------------------------
; Variable Allocation
;------------------------


;---------------------------------------------------
; Insert your custom declarations above this banner
;---------------------------------------------------
;@PSoC_UserCode_END@ (Do not change this line.)


AREA UserModules (ROM, REL)

;-----------------------------------------------------------------------------
;  FUNCTION NAME: _stateTimer_ISR
;
;  DESCRIPTION: Unless modified, this implements only a null handler stub.
;
;-----------------------------------------------------------------------------
;

_stateTimer_ISR:

   ;@PSoC_UserCode_BODY@ (Do not change this line.)
   ;---------------------------------------------------
   ; Insert your custom assembly code below this banner
   ;---------------------------------------------------
   ;   NOTE: interrupt service routines must preserve
   ;   the values of the A and X CPU registers.
   
   ;---------------------------------------------------
   ; Insert your custom assembly code above this banner
   ;---------------------------------------------------
   	mov A , [stateTimerMilisec]
	add A , [stateTimerAccuracy]
	mov [stateTimerMilisec] , A
	cmp [stateTimerMilisec], 0x0A
	jc end_timeLoop ; jump if seconds < 60
	mov [stateTimerMilisec], 0x00
	inc [stateTimerSeconds]
	cmp [stateTimerSeconds], 0x3c
	jc end_timeLoop ; jump if seconds < 60
	mov [stateTimerSeconds], 0x00
	inc [stateTimerMinutes]
	cmp [stateTimerMinutes], 0x3c
	jc end_timeLoop ; jump if minutes < 60
	mov [stateTimerMinutes], 0x00
	inc [stateTimerHour]
	cmp [stateTimerHour], 0x18
	jc end_timeLoop ; jump if hour < 24
end_timeLoop:
   ;---------------------------------------------------
   ; Insert a lcall to a C function below this banner
   ; and un-comment the lines between these banners
   ;---------------------------------------------------
   
   ;PRESERVE_CPU_CONTEXT
   ;lcall _My_C_Function
   ;RESTORE_CPU_CONTEXT
   
   ;---------------------------------------------------
   ; Insert a lcall to a C function above this banner
   ; and un-comment the lines between these banners
   ;---------------------------------------------------
   ;@PSoC_UserCode_END@ (Do not change this line.)

   reti


; end of file stateTimerINT.asm
