;;*****************************************************************************
;;*****************************************************************************
;;  FILENAME: SWINT.asm
;;   Version: 2.6, Updated on 2015/3/4 at 22:27:48
;;  Generated by PSoC Designer 5.4.3191
;;
;;  DESCRIPTION: Timer32 Interrupt Service Routine
;;-----------------------------------------------------------------------------
;;  Copyright (c) Cypress Semiconductor 2015. All Rights Reserved.
;;*****************************************************************************
;;*****************************************************************************

include "m8c.inc"
include "memory.inc"
include "SW.inc"


;-----------------------------------------------
;  Global Symbols
;-----------------------------------------------
export  _SW_ISR


AREA InterruptRAM (RAM,REL,CON)

;@PSoC_UserCode_INIT@ (Do not change this line.)
;---------------------------------------------------
; Insert your custom declarations below this banner
;---------------------------------------------------

;------------------------
; Includes
;------------------------

	
;------------------------
;  Constant Definitions
;------------------------
milisec: equ 0x10
seconds: equ 0x11
minutes: equ 0x12
hour: equ 0x13
accuracy: equ 0x20

;------------------------
; Variable Allocation
;------------------------


;---------------------------------------------------
; Insert your custom declarations above this banner
;---------------------------------------------------
;@PSoC_UserCode_END@ (Do not change this line.)


AREA UserModules (ROM, REL)

;-----------------------------------------------------------------------------
;  FUNCTION NAME: _SW_ISR
;
;  DESCRIPTION: Unless modified, this implements only a null handler stub.
;
;-----------------------------------------------------------------------------
;

_SW_ISR:

   ;@PSoC_UserCode_BODY@ (Do not change this line.)
   ;---------------------------------------------------
   ; Insert your custom assembly code below this banner
   ;---------------------------------------------------
   ;   NOTE: interrupt service routines must preserve
   ;   the values of the A and X CPU registers.
   
   ;---------------------------------------------------
   ; Insert your custom assembly code above this banner
   ;---------------------------------------------------
   	mov A , [accuracy]
	cmp A , 0x01
	jz _count_sec
	inc [milisec]
	cmp [milisec], 0x20
	jc end_timeLoop ; jump if seconds < 60
	mov [milisec], 0x00
_count_sec:	
	inc [seconds]
	cmp [seconds], 0x3c
	jc end_timeLoop ; jump if seconds < 60
	mov [seconds], 0x00
	inc [minutes]
	cmp [minutes], 0x3c
	jc end_timeLoop ; jump if minutes < 60
	mov [minutes], 0x00
	inc [hour]
end_timeLoop:
	mov    A,00
	mov    X,00
   	call   LCD_Position
   	mov    A,[hour]
   	call   LCD_PrHexByte   
	
	mov    A,00
	mov    X,02
   	call   LCD_Position
	mov    A,>COLON
   	mov    X,<COLON
   	call   LCD_PrCString
	
	mov    A,00
	mov    X,03
   	call   LCD_Position
   	mov    A,[minutes]
   	call   LCD_PrHexByte   
	
	mov    A,00
	mov    X,05
   	call   LCD_Position
	mov    A,>COLON
   	mov    X,<COLON
   	call   LCD_PrCString   
	
	mov    A,00
	mov    X,06
   	call   LCD_Position
   	mov    A,[seconds]
   	call   LCD_PrHexByte   
	
	mov    A,00
	mov    X,10
   	call   LCD_Position
	mov    A,>COLON
   	mov    X,<COLON
   	call   LCD_PrCString   
	
	mov    A,00
	mov    X,11
   	call   LCD_Position
	mov    A,[milisec]
   	call   LCD_PrHexByte    
	
.LITERAL
	COLON:
		ds  ":"
		db  00h
.ENDLITERAL
   ;---------------------------------------------------
   ; Insert a lcall to a C function below this banner
   ; and un-comment the lines between these banners
   ;---------------------------------------------------
   
   ;PRESERVE_CPU_CONTEXT
   ;lcall _My_C_Function
   ;RESTORE_CPU_CONTEXT
   
   ;---------------------------------------------------
   ; Insert a lcall to a C function above this banner
   ; and un-comment the lines between these banners
   ;---------------------------------------------------
   ;@PSoC_UserCode_END@ (Do not change this line.)

   reti


; end of file SWINT.asm
